/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firstInterface;


import DbConnection.CrudUtil;
import FeedbackInterface.FeedbackInterface;
import ManagerInterface.ManagmentInterface;
import SingUpInterface.SingUpInterface;
import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Mr.Secreti
 */
public class FirstInterface extends javax.swing.JFrame {
    
    public static String Username;
    public static String password;
    public FirstInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitLable = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JTextField();
        UserNameTxt = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        SingupButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setState(100);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLable.setBackground(new java.awt.Color(231, 8, 190));
        exitLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/8542462_window_close_icon (1).png"))); // NOI18N
        exitLable.setMaximumSize(new java.awt.Dimension(50, 50));
        exitLable.setMinimumSize(new java.awt.Dimension(50, 50));
        exitLable.setOpaque(true);
        exitLable.setPreferredSize(new java.awt.Dimension(50, 50));
        exitLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLableMouseExited(evt);
            }
        });
        jPanel4.add(exitLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, 50));

        jPanel5.setOpaque(false);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(231, 8, 190));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/9110431_minus_rectangle_f_icon.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jPanel6.setBackground(new java.awt.Color(231, 8, 190));

        jLabel5.setBackground(new java.awt.Color(66, 27, 195));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FEEDBACK MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 950, 50));

        jPanel3.setBackground(new java.awt.Color(53, 53, 53));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(2, 12, 130,200));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(2, 12, 130));
        jPanel8.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/6827784_eye_multimedia_search_ui_user interface_icon (1).png"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 50, 40));

        PasswordTxt.setBackground(new java.awt.Color(255, 175, 241));
        PasswordTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxt.setText("Enter password");
        PasswordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordTxtMouseExited(evt);
            }
        });
        PasswordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtActionPerformed(evt);
            }
        });
        jPanel7.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 320, 40));

        UserNameTxt.setBackground(new java.awt.Color(255, 175, 241));
        UserNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserNameTxt.setText("Enter user name");
        UserNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserNameTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserNameTxtMouseExited(evt);
            }
        });
        UserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTxtActionPerformed(evt);
            }
        });
        jPanel7.add(UserNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 40));

        LoginButton.setBackground(new java.awt.Color(255, 128, 204));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("LogIn");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel7.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 220, 60));

        SingupButton.setBackground(new java.awt.Color(56, 170, 130));
        SingupButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingupButton.setForeground(new java.awt.Color(255, 255, 255));
        SingupButton.setText("Sing Up");
        SingupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SingupButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SingupButtonMouseEntered(evt);
            }
        });
        SingupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingupButtonActionPerformed(evt);
            }
        });
        jPanel7.add(SingupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 347, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Not a Member ");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 390, 380));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 910, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/firstInterface/purple-sunset-4vdctecz52uxuo4v.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(950, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTxtActionPerformed

    private void UserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTxtActionPerformed

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        // TODO add your handling code here:
        // LoginButton.setBackground(Color.DarkBlue);
        LoginButton.setBackground(new java.awt.Color(231,8,190));

    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        // TODO add your handling code here:
        //   LoginButton.setBackground(Blue);
         LoginButton.setBackground(new java.awt.Color(255, 128, 204));
    }//GEN-LAST:event_LoginButtonMouseExited

    private void SingupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingupButtonActionPerformed

    private void SingupButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingupButtonMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_SingupButtonMouseEntered

    private void SingupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingupButtonMouseClicked
        // TODO add your handling code here:
        SingUpInterface singup = null;
        singup = new SingUpInterface(); //   Logger.getLogger(FirstInterface.class.getName()).log(Level.SEVERE, null, ex);
        this.setVisible(false);
        singup.setVisible(true);
        
    }//GEN-LAST:event_SingupButtonMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here
        if(UserNameTxt.getText().equals("ManAdmin"))
        {
            ManagmentInterface manint = new ManagmentInterface();
            this.setVisible(false);
            manint.setVisible(true);
            
            
        }
        else if(UserNameTxt.getText().equals("CusAdmin"))
        {
            FeedbackInterface feedint = null;
            feedint = new FeedbackInterface();

        }    
        

        

        
        

    }//GEN-LAST:event_LoginButtonMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void exitLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLableMouseEntered
        // TODO add your handling code here:
        exitLable.setBackground(Color.red);
    }//GEN-LAST:event_exitLableMouseEntered

    private void exitLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLableMouseExited
        // TODO add your handling code here:
        exitLable.setBackground(new java.awt.Color(231, 8, 139));
    }//GEN-LAST:event_exitLableMouseExited

    private void exitLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLableMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLableMouseClicked

    private void UserNameTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameTxtMouseEntered
        // TODO add your handling code here:
        if("Enter user name".equals(UserNameTxt.getText())){
        UserNameTxt.setText("");
        }
    }//GEN-LAST:event_UserNameTxtMouseEntered

    private void UserNameTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameTxtMouseExited
        // TODO add your handling code here:
        if("".equals(UserNameTxt.getText())){
            UserNameTxt.setText("Enter user name");
        }
    }//GEN-LAST:event_UserNameTxtMouseExited

    private void PasswordTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTxtMouseEntered
        // TODO add your handling code here:
        if("Enter password".equals(PasswordTxt.getText())){
        PasswordTxt.setText("");
        }
    }//GEN-LAST:event_PasswordTxtMouseEntered

    private void PasswordTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTxtMouseExited
        // TODO add your handling code here:
                if("".equals(PasswordTxt.getText())){
            PasswordTxt.setText("Enter password");
        }
    }//GEN-LAST:event_PasswordTxtMouseExited

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:

String Uname = UserNameTxt.getText();
String pass = PasswordTxt.getText();
Username = Uname;
password = pass;
if (Uname.length() >= 3) {
    if (Uname.substring(0, 3).equalsIgnoreCase("MAN")) {
        try {
            ResultSet result = CrudUtil.execute("SELECT * FROM manager WHERE MANAGER_ID=?", Uname);
            
            if (result.next()) { // Check if a row was found in the result set
                String dbpas = result.getString("MANAGER_PASSWORD"); 
                if (dbpas.equals(pass)) {
                    ManagmentInterface manint = new ManagmentInterface();
                    this.setVisible(false);
                    manint.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Re-Check Password and Try again..");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Your account cannot find.\nPlease Re-check username");
            }
        } catch (SQLException | ClassNotFoundException ex) {
        }
    } else if (Uname.substring(0, 3).equalsIgnoreCase("CUS")) {
        try {
            ResultSet result = CrudUtil.execute("SELECT * FROM customer WHERE CUSTOMER_ID=?", Uname);
            
            if (result.next()) { 
                String dbpas = result.getString("CUSTOMER_PASSWORD"); 
                if (dbpas.equals(pass)) {
                    FeedbackInterface feedint = new FeedbackInterface();
                    this.setVisible(false);
                    feedint.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Re-Check Password and Try again..");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Your account cannot find.\nPlease Re-check username");
            }
        } catch (SQLException | ClassNotFoundException ex) {
        }
    } else {
        JOptionPane.showMessageDialog(null, "Re-check your User Id or use Capital letters and try again!..");
    }
} else {
    JOptionPane.showMessageDialog(null, "Username must be at least 3 characters long.");
}



        
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FirstInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JButton SingupButton;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JLabel exitLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables

    private String Usename(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String Username(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
