/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FeedbackInterface;

import DbConnection.CrudUtil;
import SingUpInterface.SingUpInterface;
import firstInterface.FirstInterface;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Mr.Secreti
 */
public final class FeedbackInterface extends javax.swing.JFrame {


    public int x;
    /**
     * Creates new form FeedbackInterface
     */
    public FeedbackInterface() {
        initComponents();
        myclass();
        try {
            startOpton();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FeedbackInterface.class.getName()).log(Level.SEVERE, null, ex);
        }

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cusid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FEEDBACKIDL = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cusname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sernpro = new javax.swing.JRadioButton();
        ser = new javax.swing.JRadioButton();
        pro = new javax.swing.JRadioButton();
        Barchart = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        orange = new javax.swing.JLabel();
        yellow = new javax.swing.JLabel();
        lightGreen = new javax.swing.JLabel();
        Green = new javax.swing.JLabel();
        red = new javax.swing.JLabel();
        bigred = new javax.swing.JLabel();
        bigGreen = new javax.swing.JLabel();
        bigOrange = new javax.swing.JLabel();
        bigYellow = new javax.swing.JLabel();
        bigLightGreen = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentTxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(231, 8, 190));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/8542462_window_close_icon (1).png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, 50));

        jPanel5.setOpaque(false);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(231, 8, 190));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/9110431_minus_rectangle_f_icon.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jPanel6.setBackground(new java.awt.Color(231, 8, 190));

        jLabel5.setBackground(new java.awt.Color(66, 27, 195));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FEEDBACK MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 50));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 128, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Log Out");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel10.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 132, 50));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 950, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(2, 12, 130,100));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer ID");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cusid.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cusid.setForeground(new java.awt.Color(255, 255, 0));
        jPanel7.add(cusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer Feedback ID");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        FEEDBACKIDL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        FEEDBACKIDL.setForeground(new java.awt.Color(255, 255, 0));
        jPanel7.add(FEEDBACKIDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FEEDBACK Type");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        cusname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cusname.setForeground(new java.awt.Color(255, 255, 0));
        jPanel7.add(cusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Customer Name");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        buttonGroup1.add(sernpro);
        sernpro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sernpro.setForeground(new java.awt.Color(255, 255, 255));
        sernpro.setText("Service & Product");
        sernpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sernproActionPerformed(evt);
            }
        });
        jPanel7.add(sernpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        buttonGroup1.add(ser);
        ser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ser.setForeground(new java.awt.Color(255, 255, 255));
        ser.setText("Service");
        ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serActionPerformed(evt);
            }
        });
        jPanel7.add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        buttonGroup1.add(pro);
        pro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pro.setForeground(new java.awt.Color(255, 255, 255));
        pro.setText("Product");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        jPanel7.add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 390));

        Barchart.setBackground(new java.awt.Color(2, 12, 130,100));
        Barchart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/orange.png"))); // NOI18N
        orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orangeMouseClicked(evt);
            }
        });
        jPanel8.add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 70, 80));

        yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/3.png"))); // NOI18N
        yellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowMouseClicked(evt);
            }
        });
        jPanel8.add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 20, 70, 80));

        lightGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/4.png"))); // NOI18N
        lightGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lightGreenMouseClicked(evt);
            }
        });
        jPanel8.add(lightGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 70, 80));

        Green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/5.png"))); // NOI18N
        Green.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreenMouseClicked(evt);
            }
        });
        jPanel8.add(Green, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 20, 70, 80));

        red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/angry 1.png"))); // NOI18N
        red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                redMouseEntered(evt);
            }
        });
        jPanel8.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 70, 80));

        bigred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/1.png"))); // NOI18N
        bigred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bigredMouseEntered(evt);
            }
        });
        jPanel8.add(bigred, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        bigGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/5-1.png"))); // NOI18N
        bigGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bigGreenMouseEntered(evt);
            }
        });
        jPanel8.add(bigGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 110, 110));

        bigOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/2.png"))); // NOI18N
        bigOrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bigOrangeMouseEntered(evt);
            }
        });
        jPanel8.add(bigOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 110));

        bigYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/3-1.png"))); // NOI18N
        bigYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bigYellowMouseEntered(evt);
            }
        });
        jPanel8.add(bigYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 110));

        bigLightGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackInterface/images/4-1.png"))); // NOI18N
        bigLightGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bigLightGreenMouseEntered(evt);
            }
        });
        jPanel8.add(bigLightGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 110, 110));

        Barchart.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 590, 120));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CommentTxt.setBackground(new java.awt.Color(255, 175, 241));
        CommentTxt.setColumns(20);
        CommentTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CommentTxt.setForeground(new java.awt.Color(255, 255, 255));
        CommentTxt.setRows(5);
        CommentTxt.setText("Enter your comment here.....");
        CommentTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CommentTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CommentTxtMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(CommentTxt);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 530, 130));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cansel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, 40));

        jButton3.setBackground(new java.awt.Color(255, 128, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Done");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 100, 40));

        Barchart.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 550, 240));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select your Mood from here");
        Barchart.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jPanel3.add(Barchart, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 620, 390));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 910, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/firstInterface/purple-sunset-4vdctecz52uxuo4v.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(950, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void myclass(){
        boolean False = false;
        bigred.setVisible(False);
        bigOrange.setVisible(False);
        bigYellow.setVisible(False);
        bigLightGreen.setVisible(False);
        bigGreen.setVisible(False);
    }
    private void startOpton() throws SQLException, ClassNotFoundException{
    try {
        // Retrieve the customer data
        ResultSet result = CrudUtil.execute("SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=?", FirstInterface.Username);

        if (result.next()) {
            String CUSid = result.getString("CUSTOMER_ID");
            cusid.setText(CUSid);

            String fname = result.getString("CUSTOMER_FIRST_NAME");
            String lname = result.getString("CUSTOMER_LAST_NAME");
            cusname.setText(fname + " " + lname);
        } else {
            // Handle the case where no data is found for the given CUSTOMER_ID
            JOptionPane.showMessageDialog(null, "Customer not found.");
        }

        // Retrieve the last record from CUSTOMER_FEEDBACK table
        ResultSet feedbackResult = CrudUtil.execute("SELECT * FROM CUSTOMER_FEEDBACK");

        if (feedbackResult.next()) {
            String lastFeedbackId = feedbackResult.getString("CUSTOMER_FEEDBACK_ID");

            // Extract the numeric part of the last feedback ID
            String numericPart = lastFeedbackId.replaceAll("[^0-9]", "");

            
            int nextNumericPart = Integer.parseInt(numericPart) ;
            String nextFeedbackId = "feed" + String.format("%03d", nextNumericPart);

            FEEDBACKIDL.setText(nextFeedbackId);
        } else {
            
            JOptionPane.showMessageDialog(null, "No feedback data found.");
        }

    } catch (SQLException | ClassNotFoundException ex) {
        
        JOptionPane.showMessageDialog(null, "Error accessing the database.");
    }



        

    }
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sernproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sernproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sernproActionPerformed

    private void serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CommentTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommentTxtMouseEntered
        // TODO add your handling code here:
        if("Enter your comment here.....".equals(CommentTxt.getText()))
        {
            CommentTxt.setText("");
        }
    }//GEN-LAST:event_CommentTxtMouseEntered

    private void CommentTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommentTxtMouseExited
        // TODO add your handling code here:
                if("".equals(CommentTxt.getText()))
        {
            CommentTxt.setText("Enter your comment here.....");
        }
    }//GEN-LAST:event_CommentTxtMouseExited

    private void bigGreenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigGreenMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bigGreenMouseEntered

    private void redMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redMouseEntered
        boolean True = false;
        // TODO add your handling code here:
        //red.setVisible(False);
        bigred.setVisible(True);
        
    }//GEN-LAST:event_redMouseEntered

    private void bigredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigredMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bigredMouseEntered

    private void bigOrangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigOrangeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bigOrangeMouseEntered

    private void bigYellowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigYellowMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bigYellowMouseEntered

    private void bigLightGreenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigLightGreenMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bigLightGreenMouseEntered

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        FirstInterface FI = new FirstInterface();
        FI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String rate_type = null;
        String type = null;
        switch (x) {
            case 1 -> {
                type = "very bad";
            }
            case 2 -> {
                type = "bad";
            }
            case 3 -> {
                type = "average";
            }
            case 4 -> {
                type = "good";
            }
            case 5 -> {
                type = "excellent";
            }
            default -> {
                JOptionPane.showMessageDialog(null, "Please Give a reaction by clicking the face.");
            }
        }

        if (ser.isSelected()) {
            rate_type = "Service";
        } else if (pro.isSelected()) {
            rate_type = "Product";
        } else if (sernpro.isSelected()) {
            rate_type = "Service and Product";
        }
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = new Date();
        String Date = formatter.format(date);

        String feedid = FEEDBACKIDL.getText();
        String Rate = type;
        String Comment = CommentTxt.getText();
        String type1 = rate_type;
        String Customer = cusid.getText();

        try {
            CrudUtil.execute("INSERT INTO CUSTOMER_FEEDBACK (CUSTOMER_FEEDBACK_ID, DATE, CUSTOMER_RATING, COMMENT, TYPE, CUSTOMER_ID) VALUES (?, ?, ?, ?, ?, ?)",
                    feedid, Date, Rate, Comment, type1, Customer);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SingUpInterface.class.getName()).log(Level.SEVERE, null, ex);
            // Handle the exception appropriately, e.g., show an error message.
            JOptionPane.showMessageDialog(null, "Error inserting feedback data.");
        }
   
        JOptionPane.showMessageDialog(null, "Thank you for your feedback sir..");    
    }//GEN-LAST:event_jButton3MouseClicked

    private void redMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redMouseClicked
        // TODO add your handling code here:
        x=1;
        JOptionPane.showMessageDialog(null, "Rating Recoderd");
    }//GEN-LAST:event_redMouseClicked

    private void orangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeMouseClicked
        // TODO add your handling code here:
        x=2;
        JOptionPane.showMessageDialog(null, "Rating Recoderd");
    }//GEN-LAST:event_orangeMouseClicked

    private void yellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowMouseClicked
        // TODO add your handling code here:
        x=3;
        JOptionPane.showMessageDialog(null, "Rating Recoderd");
    }//GEN-LAST:event_yellowMouseClicked

    private void lightGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lightGreenMouseClicked
        // TODO add your handling code here:
        x=4;
        JOptionPane.showMessageDialog(null, "Rating Recoderd");
    }//GEN-LAST:event_lightGreenMouseClicked

    private void GreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreenMouseClicked
        // TODO add your handling code here:
        x=5;
        JOptionPane.showMessageDialog(null, "Rating Recoderd");
    }//GEN-LAST:event_GreenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FeedbackInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barchart;
    private javax.swing.JTextArea CommentTxt;
    private javax.swing.JLabel FEEDBACKIDL;
    private javax.swing.JLabel Green;
    private javax.swing.JLabel bigGreen;
    private javax.swing.JLabel bigLightGreen;
    private javax.swing.JLabel bigOrange;
    private javax.swing.JLabel bigYellow;
    private javax.swing.JLabel bigred;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cusid;
    private javax.swing.JLabel cusname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lightGreen;
    private javax.swing.JLabel orange;
    private javax.swing.JRadioButton pro;
    private javax.swing.JLabel red;
    private javax.swing.JRadioButton ser;
    private javax.swing.JRadioButton sernpro;
    private javax.swing.JLabel yellow;
    // End of variables declaration//GEN-END:variables
}
